/* auto-generated by NAPI-RS */
/* eslint-disable */
/** A parsed GraphQL schema that can be reused to extract coordinates from multiple documents */
export declare class ParsedSchema {
  /** Create a new ParsedSchema from a schema string */
  constructor(schemaText: string)
  /** Extract schema coordinates from a document using this parsed schema */
  extractSchemaCoordinates(documentText: string): Array<string>
}
